Create submit form route
FACN1/litter-app pull request #61
Opened 2017-05-01 16:11 UTC by edgarfinn

2017-05-01 19:49 UTC, JWLD commented on src/handlebars/views/report.hbs
> +    <button class="form-button" id="getLocationButton" type="button" name="location">Submit Location</button>
probs best to stick to one naming convention - I think we've gone for kebab case in most places, so maybe change to get-location-button

2017-05-01 19:51 UTC, JWLD commented on public/script/report.js
> +    if (navigator.geolocation) {
indentation ✌️

2017-05-01 19:51 UTC, JWLD commented on public/script/report.js
> +var locationButton = document.getElementById('getLocationButton');
might be good to wrap all this code in an IIFE

2017-05-01 19:53 UTC, JWLD commented on public/script/report.js
> +}
missing semicolon - also on lines 15, 16, 18

2017-05-01 19:56 UTC, JWLD commented on public/script/report.js
> +locationButton.addEventListener('click', getLocation)
why separate getLocation out? you could even get away with not having any variables, e.g.
```
document.getElementById('getLocationButton').addEventListener('click', function() {
    ...
});
```

2017-05-01 20:00 UTC, jwld requested changes
just a few suggestions in report.js and report.hbs

2017-05-01 20:01 UTC, JWLD commented on public/script/report.js
> +        x.innerHTML = "Geolocation is not supported by this browser.";
what's x?

2017-05-01 20:05 UTC, JWLD commented on public/script/report.js
> +var locationButton = document.getElementById('getLocationButton');
by all this code I mean the whole file

2017-05-01 20:10 UTC, JWLD commented on public/style/sass/_report.scss
> +  padding: 0.5em;
got padding twice here - the second overwrites the first (line 22)

2017-05-01 20:10 UTC, JWLD commented on public/style/sass/_report.scss
> +  padding: 0.5em;
same with background color

2017-05-02 07:20 UTC, edgarfinn commented on src/handlebars/views/report.hbs
> +    <button class="form-button" id="getLocationButton" type="button" name="location">Submit Location</button>
Classes: kebab. Id's: Camel

2017-05-02 07:23 UTC, edgarfinn commented on public/script/report.js
> +    if (navigator.geolocation) {
done

2017-05-02 07:39 UTC, edgarfinn commented on public/script/report.js
> +}
done. 

And for now just logging out the error message

2017-05-02 07:55 UTC, merged